# Generated by Django 3.1.4 on 2021-01-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
    ]
