# Generated by Django 3.1.4 on 2021-01-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_text', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
        migrations.DeleteModel(
            name='note',
        ),
    ]
